; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

lib_deps =
	lvgl
	bodmer/TFT_eSPI
	ESP32_Host_MIDI@6.0.1
	AppleMIDI
	ESPmDNS
build_flags = 	
	-D LV_CONF_INCLUDE_SIMPLE
    -I include ; Tells the compiler where to look for lv_conf.h
	-D ARDUINO_USB_CDC_ON_BOOT=1
	; -D ARDUINO_USB_MODE=0	; USB-OTG (TinyUSB) — required for USB MIDI device + Serial CDC

[env:esp32-s3]
build_flags = 
	${env.build_flags}     
	-D USER_SETUP_LOADED=1
	-include $PROJECT_DIR/include/User_Setup_ILI9341_XPT2046.h

[env:esp32-s3-wokwi]
lib_ldf_mode = deep ; This fixes missing symbols for WokWi
lib_deps = 
	${env.lib_deps}
    adafruit/Adafruit FT6206 Library   
build_flags = 
	${env.build_flags}
	-D USER_SETUP_LOADED=1
	-D WOKWI=1
	-include $PROJECT_DIR/include/User_Setup_ILI9341_FT6206.h
	-DAPPLEMIDI_INITIATOR
	

